export const styles = {
  app: {
    minHeight: "100vh",
    maxWidth: 480,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    background: "#F7F6F3",
  },
  loadingScreen: { display: "flex", alignItems: "center", justifyContent: "center", height: "100vh", color: "#8A8A86", fontSize: 14 },

  // Login
  loginScreen: { display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", padding: 20 },
  loginCard: { background: "#fff", borderRadius: 16, padding: 28, width: "100%", maxWidth: 360, border: "1px solid #ECEAE3" },
  loginBrand: { fontWeight: 800, fontSize: 22, color: "#1F4D45", textAlign: "center" },
  loginLogo: { width: 90, height: 90, objectFit: "contain", display: "block", margin: "0 auto" },
  loginSub: { fontSize: 13, color: "#9A9A94", textAlign: "center", marginBottom: 20, marginTop: 4 },
  errorBox: { background: "#FBF1E7", color: "#7A4B26", fontSize: 12.5, padding: "8px 12px", borderRadius: 8, margin: "10px 0" },
  linkBtn: { width: "100%", background: "transparent", border: "none", color: "#1F4D45", fontSize: 13, fontWeight: 600, marginTop: 14, cursor: "pointer", textAlign: "center" },

  // Top bar
  topbar: { background: "#FFFFFF", borderBottom: "1px solid #E8E6DF", position: "sticky", top: 0, zIndex: 10 },
  topbarRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 18px 10px" },
  brand: { fontWeight: 800, fontSize: 17, letterSpacing: "-0.01em", color: "#1F4D45" },
  topbarLogo: { width: 34, height: 34, objectFit: "contain", borderRadius: 8 },
  brandSub: { fontSize: 11.5, color: "#9A9A94", marginTop: 1 },
  statusPill: { display: "flex", alignItems: "center", gap: 6, border: "none", borderRadius: 20, padding: "6px 12px", fontSize: 12, fontWeight: 600 },
  statusOn: { background: "#E4EFE9", color: "#1F4D45" },
  statusOff: { background: "#F6E6DA", color: "#A85A2A" },
  iconBtn: { background: "#F1EFE8", border: "none", borderRadius: 8, padding: 7, cursor: "pointer", display: "flex", color: "#5C5C58" },
  syncBar: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "#FBF1E7", padding: "8px 18px", fontSize: 12.5, color: "#7A4B26", borderTop: "1px solid #F0DDC8" },
  syncBarLeft: { display: "flex", alignItems: "center", gap: 6 },
  syncBtn: { display: "flex", alignItems: "center", gap: 5, background: "#1F4D45", color: "#fff", border: "none", borderRadius: 8, padding: "6px 10px", fontSize: 12, fontWeight: 600, cursor: "pointer" },

  content: { flex: 1, padding: "16px 16px 90px", overflowY: "auto" },
  h1: { fontSize: 20, fontWeight: 800, letterSpacing: "-0.01em", margin: 0 },
  listHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  backHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14 },
  backHeaderRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  editLinkBtn: { background: "#1F4D45", color: "#fff", border: "none", borderRadius: 9, padding: "7px 14px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  dangerLinkBtn: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", width: "100%", background: "transparent", color: "#B8763E", border: "1px solid #F0DDC8", borderRadius: 12, padding: "12px 0", fontSize: 13.5, fontWeight: 600, marginTop: 16, cursor: "pointer" },
  exportPdfBtn: { display: "flex", alignItems: "center", gap: 7, justifyContent: "center", width: "100%", background: "#fff", color: "#1F4D45", border: "1.5px solid #1F4D45", borderRadius: 12, padding: "12px 0", fontSize: 14, fontWeight: 700, marginTop: 18, cursor: "pointer" },
  agendaHeaderRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  viewToggle: { display: "flex", background: "#F1EFE8", borderRadius: 9, padding: 3, gap: 2 },
  viewToggleBtn: { border: "none", background: "transparent", padding: "7px 10px", borderRadius: 7, cursor: "pointer", color: "#8A8A86", display: "flex" },
  viewToggleBtnActive: { background: "#fff", color: "#1F4D45", boxShadow: "0 1px 2px rgba(0,0,0,0.06)" },
  fabFullWidth: { width: "100%", background: "#1F4D45", color: "#fff", border: "none", borderRadius: 12, padding: "12px 0", fontSize: 14, fontWeight: 700, marginBottom: 18, cursor: "pointer" },
  calMesNav: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  calNavBtn: { background: "#fff", border: "1px solid #E8E6DF", borderRadius: 9, padding: 6, cursor: "pointer", display: "flex" },
  calMesLabel: { fontSize: 15.5, fontWeight: 700, color: "#22231F" },
  calGridHeader: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", marginBottom: 6 },
  calDiaSemana: { textAlign: "center", fontSize: 11, color: "#9A9A94", fontWeight: 600 },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 4 },
  calCelulaVazia: { aspectRatio: "1" },
  calCelula: { aspectRatio: "1", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", border: "none", background: "transparent", borderRadius: 10, cursor: "pointer", gap: 3, position: "relative" },
  calCelulaDia: { fontSize: 13.5, fontWeight: 600, color: "#22231F" },
  calCelulaPonto: { width: 5, height: 5, borderRadius: "50%", background: "#1F4D45" },
  calCelulaHoje: { background: "#E4EFE9" },
  calCelulaSelecionada: { background: "#1F4D45" },
  backBtn: { background: "#fff", border: "1px solid #E8E6DF", borderRadius: 10, padding: 6, cursor: "pointer", display: "flex" },
  fabInline: { display: "flex", alignItems: "center", gap: 5, background: "#1F4D45", color: "#fff", border: "none", borderRadius: 10, padding: "8px 13px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  sectionTitle: { fontSize: 12.5, fontWeight: 700, color: "#8A8A86", textTransform: "uppercase", letterSpacing: "0.04em", margin: "20px 4px 8px" },
  emptyHint: { color: "#9A9A94", fontSize: 13.5, padding: "24px 8px", textAlign: "center" },
  card: { background: "#fff", borderRadius: 14, padding: "4px 16px", border: "1px solid #ECEAE3" },
  rowCard: { display: "flex", alignItems: "center", gap: 12, background: "#fff", borderRadius: 12, padding: "12px 14px", border: "1px solid #ECEAE3", marginBottom: 8, fontSize: 14 },
  listItem: { display: "flex", alignItems: "center", gap: 12, width: "100%", background: "#fff", borderRadius: 12, padding: "12px 14px", border: "1px solid #ECEAE3", marginBottom: 8, cursor: "pointer", textAlign: "left" },
  avatar: { width: 38, height: 38, borderRadius: 10, background: "#E4EFE9", color: "#1F4D45", fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  listItemTitle: { fontWeight: 600, fontSize: 14.5 },
  listItemSub: { fontSize: 12.5, color: "#9A9A94", marginTop: 2 },
  dateBadge: { width: 44, height: 44, borderRadius: 10, background: "#1F4D45", color: "#fff", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  dateBadgeDay: { fontWeight: 800, fontSize: 15, lineHeight: 1 },
  dateBadgeMonth: { fontSize: 9, letterSpacing: "0.05em", marginTop: 1 },
  field: { display: "block", padding: "10px 0", borderBottom: "1px solid #F1EFE8" },
  fieldLabel: { fontSize: 11.5, color: "#9A9A94", marginBottom: 4, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.03em" },
  fieldValue: { fontSize: 14.5, color: "#22231F" },
  input: { width: "100%", border: "none", outline: "none", fontSize: 15, color: "#22231F", background: "transparent", padding: 0, fontFamily: "inherit" },
  divider: { height: 1, background: "#F1EFE8", margin: "4px 0" },
  payRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 0" },
  payToggle: { display: "flex", background: "#F1EFE8", borderRadius: 9, padding: 3, gap: 2 },
  payBtn: { border: "none", background: "transparent", padding: "6px 12px", borderRadius: 7, fontSize: 12.5, fontWeight: 600, cursor: "pointer", color: "#8A8A86" },
  payBtnActivePending: { background: "#fff", color: "#A85A2A", boxShadow: "0 1px 2px rgba(0,0,0,0.06)" },
  payBtnNaoRealizada: { background: "#C24E3A", color: "#fff" },
  statusToggle3: { display: "flex", flexDirection: "column", gap: 8, marginTop: 4 },
  statusBtn3: { border: "1px solid #ECEAE3", background: "#fff", padding: "10px 12px", borderRadius: 9, fontSize: 13, fontWeight: 600, cursor: "pointer", color: "#5C5C58", textAlign: "left" },
  statusBtn3Pendente: { background: "#FBF1E7", color: "#A85A2A", borderColor: "#F0DDC8" },
  statusBtn3Realizada: { background: "#E4EFE9", color: "#1F4D45", borderColor: "#CDE3D9" },
  statusBtn3NaoRealizada: { background: "#FBE2DC", color: "#C24E3A", borderColor: "#F2C9BD" },
  payBtnActivePaid: { background: "#1F4D45", color: "#fff" },
  kmRow: { display: "flex", gap: 16 },
  kmResult: { display: "flex", alignItems: "center", gap: 6, fontSize: 13.5, padding: "10px 0 6px", color: "#3D3D38" },
  errorText: { display: "flex", alignItems: "center", gap: 5, fontSize: 12, color: "#B8763E", padding: "4px 0" },
  fotosGrid: { display: "flex", flexWrap: "wrap", gap: 10, padding: "10px 0" },
  fotoWrapper: { position: "relative", width: 72, height: 72 },
  fotoMiniatura: { width: 72, height: 72, borderRadius: 10, objectFit: "cover", border: "1px solid #ECEAE3" },
  fotoRemoveBtn: { position: "absolute", top: -6, right: -6, background: "#22231F", color: "#fff", border: "none", borderRadius: "50%", width: 20, height: 20, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  fotoAddBtn: { width: 72, height: 72, borderRadius: 10, border: "1.5px dashed #C9C7BE", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", background: "#FAF9F6" },
  fotoFormItem: { display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid #F1EFE8" },
  fotoDescricaoInput: { flex: 1, border: "1px solid #E8E6DF", borderRadius: 8, padding: "8px 10px", fontSize: 13, fontFamily: "inherit", color: "#22231F", background: "#FAF9F6" },
  fotoAddBtnFull: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, width: "100%", borderRadius: 10, border: "1.5px dashed #C9C7BE", padding: "12px 0", cursor: "pointer", background: "#FAF9F6", marginTop: 10 },
  fotosDetalheLista: { display: "flex", flexDirection: "column", gap: 12 },
  fotoDetalheItem: { background: "#fff", borderRadius: 12, border: "1px solid #ECEAE3", overflow: "hidden" },
  fotoDetalheImg: { width: "100%", maxHeight: 280, objectFit: "cover", display: "block" },
  fotoDetalheDescricao: { padding: "10px 12px", fontSize: 13.5, color: "#3D3D38" },
  documentoRow: { display: "flex", alignItems: "center", gap: 10, padding: "12px 0", borderBottom: "1px solid #F1EFE8", textDecoration: "none", color: "#22231F" },
  documentoNome: { fontSize: 13.5, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  documentoFormItem: { display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid #F1EFE8" },
  documentoRemoveBtn: { background: "transparent", border: "none", color: "#B8763E", cursor: "pointer", padding: 4, display: "flex" },
  totalDespesasCard: { background: "#1F4D45", borderRadius: 14, padding: "16px 18px", display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  totalDespesasLabel: { color: "#CFE3DC", fontSize: 13 },
  totalDespesasValor: { color: "#fff", fontSize: 19, fontWeight: 800 },
  despesaValor: { fontWeight: 700, fontSize: 14, color: "#22231F" },
  saldoCard: { background: "#1F4D45", borderRadius: 14, padding: "18px 18px", marginBottom: 16 },
  saldoLabel: { color: "#CFE3DC", fontSize: 12.5, marginBottom: 6 },
  saldoValor: { color: "#fff", fontSize: 26, fontWeight: 800 },
  gestaoGrid: { display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 6 },
  gestaoCard: { background: "#fff", borderRadius: 12, border: "1px solid #ECEAE3", padding: "12px 14px", flex: "1 1 calc(50% - 5px)", minWidth: 120 },
  gestaoCardHeader: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#5C5C58", marginBottom: 6 },
  gestaoCardValor: { fontSize: 16.5, fontWeight: 800, color: "#22231F" },
  categoriaRow: { display: "flex", alignItems: "center", gap: 10, padding: "11px 0", borderBottom: "1px solid #F1EFE8" },
  categoriaNome: { flex: 1, fontSize: 13.5 },
  categoriaPercentual: { fontSize: 11.5, color: "#9A9A94" },
  categoriaValor: { fontSize: 13.5, fontWeight: 700, minWidth: 80, textAlign: "right" },
  integracaoRow: { display: "flex", alignItems: "center", gap: 12, padding: "8px 0 16px" },
  integracaoIconBox: { width: 40, height: 40, borderRadius: 10, background: "#E4EFE9", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  linkExternoRow: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", color: "#1F4D45", fontSize: 13, fontWeight: 600, textDecoration: "none", padding: "16px 0" },
  offlineNotice: { display: "flex", alignItems: "flex-start", gap: 8, background: "#FBF1E7", color: "#7A4B26", fontSize: 12.5, padding: "10px 12px", borderRadius: 10, marginBottom: 12, lineHeight: 1.4 },
  primaryBtn: { width: "100%", background: "#1F4D45", color: "#fff", border: "none", borderRadius: 12, padding: "14px 0", fontSize: 15, fontWeight: 700, marginTop: 20, cursor: "pointer" },
  primaryBtnDisabled: { background: "#D8D6CD", color: "#A8A6A0", cursor: "not-allowed" },
  tag: { fontSize: 10.5, fontWeight: 700, padding: "3px 8px", borderRadius: 6 },
  tagPaid: { background: "#E4EFE9", color: "#1F4D45" },
  tagPending: { background: "#F6E6DA", color: "#A85A2A" },
  tagNaoRealizada: { background: "#FBE2DC", color: "#C24E3A" },
  tagSync: { display: "flex", alignItems: "center", gap: 3, fontSize: 9.5, color: "#B8763E" },
  bottomNav: { display: "flex", background: "#fff", borderTop: "1px solid #E8E6DF", position: "sticky", bottom: 0, paddingBottom: 6 },
  navBtn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "10px 0 4px", background: "transparent", border: "none", fontSize: 9.5, cursor: "pointer" },
  toast: { position: "fixed", bottom: 78, left: "50%", transform: "translateX(-50%)", background: "#22231F", color: "#fff", padding: "10px 18px", borderRadius: 10, fontSize: 13, maxWidth: 360, textAlign: "center", boxShadow: "0 8px 24px rgba(0,0,0,0.2)", zIndex: 50 },
};
